### PR TITLE
Fix msrv check by pinning `home` dependency

### PR DESCRIPTION
**Pull request by nicklan**
## What changes are proposed in this pull request?

`hdfs-native` depends on `which` which depends on `home`. `home` recently updated and bumped their msrv to 1.81. This pins us to the previous version.

## How was this change tested?

Check that the msrv test now passes

### CODE REVIEW

**Comment by OussamaSaoudi-db** [comment]
Seems like we'd need to manually update this if we want to stay up to date with hdfs/home. Is this a problem if we forget or leave it at this version?

**Review by zachschuermann — APPROVED** [review]
LGTM! also is there a way to get better output in the CI job? failing was just showing 'exited with code 1'

**Comment by nicklan** [comment]
> LGTM! also is there a way to get better output in the CI job? failing was just showing 'exited with code 1'

Yeah, there are some options. I didn't enable them here since I think in general checking locally should repo things as long as we remember to `cargo update`

**Review by roeap — APPROVED** [review]
just needed to do the exact same change in delta-rs ...

**Comment by zachschuermann** [comment]
> > LGTM! also is there a way to get better output in the CI job? failing was just showing 'exited with code 1'
> 
> Yeah, there are some options. I didn't enable them here since I think in general checking locally should repo things as long as we remember to `cargo update`

Lol yea the 'remember to `cargo update`' is what i didn't do..

**Review by OussamaSaoudi-db — APPROVED** [review]

**Comment by OussamaSaoudi-db** [comment]
> Yeah, if hdfs-native updates and needs a newer version of home we'll either have to pin an older version of that crate or bump our msrv. We can deal with that as needed.

Ahh so it will fail compilation and tell us we need to update home. That's good. thx!

**Pull request merged**
