### PR TITLE
add MSRV

### PR DESCRIPTION
**Pull request by zachschuermann**
add MSRV and test it in CI with `cargo-msrv`. currently set to rust `1.80` (version when `LazyLock` was introduced)

### CODE REVIEW

**Comment by hntd187** [comment]
Unpopular suggestion, but do you want to run this on other operating systems as well?

**Comment by zachschuermann** [comment]
> Unpopular suggestion, but do you want to run this on other operating systems as well?

Do we forsee changes going in to specific OSes causing us to bump MSRV? given that it seems like we don't leverage much OS-specific things I deemed this low risk and only ran on linux for speed :)

**Comment by hntd187** [comment]
Your changes fail on windows which was why I asked :)

**Comment by zachschuermann** [comment]
Lol welp sounds like we should check on windows then too :(

**Comment by scovich** [comment]
> > > Unpopular suggestion, but do you want to run this on other operating systems as well?
> > 
> > Do we forsee changes going in to specific OSes causing us to bump MSRV? given that it seems like we don't leverage much OS-specific things I deemed this low risk and only ran on linux for speed :)
> 
> Your changes fail on windows which was why I asked :)

What windows-specific thing did we trip over? I thought MSRV was about rust versions, not OS versions -- and I wasn't aware that rust ever stabilized new features for only a subset of OS?

**Comment by scovich** [comment]
> What windows-specific thing did we trip over? I thought MSRV was about rust versions, not OS versions -- and I wasn't aware that rust ever stabilized new features for only a subset of OS?

From the https://github.com/delta-io/delta-kernel-rs/actions/runs/11900799862/job/33162411135?pr=504, it looks like the MSRV script itself simply failed to run for some unknown reason?
```
cargo msrv --path kernel/ verify --all-features
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
Error: Process completed with exit code 1.
```

**Review by nicklan — APPROVED** [review]

**Comment by OussamaSaoudi-db** [comment]
Not sure if we need this right away, but I'd like to see a policy on when we are allowed to update MSRV. For example, Datafusion clearly communicates [when it's safe to update MSRV](https://github.com/apache/datafusion?tab=readme-ov-file#rust-version-compatibility-policy).

**Comment by zachschuermann** [comment]
> Not sure if we need this right away, but I'd like to see a policy on when we are allowed to update MSRV. For example, Datafusion clearly communicates [when it's safe to update MSRV](https://github.com/apache/datafusion?tab=readme-ov-file#rust-version-compatibility-policy).

let's take that as future work :) no real need right now

**Review by OussamaSaoudi-db — APPROVED** [review]

**Pull request merged**
